### ISSUE TITLE
NServiceBus Performance Counters install failed

### ISSUE THREAD

**Issue by RonckVac** [Particular/Packages.PerfCounters#1]
Hello,
I just downloaded the "Particular Service Platform Installer"
ran the setup.exe and this exception was shown.

System.InvalidOperationException: Cannot load Counter Name data because an invalid index '' was read from the registry.
   at System.Diagnostics.PerformanceCounterLib.GetStringTable(Boolean isHelp)
   at System.Diagnostics.PerformanceCounterLib.get_NameTable()
   at System.Diagnostics.PerformanceCounterLib.get_CategoryTable()
   at System.Diagnostics.PerformanceCounterLib.CategoryExists(String machine, String category)
   at System.Diagnostics.PerformanceCounterCategory.Exists(String categoryName, String machineName)
   at System.Diagnostics.PerformanceCounterCategory.Exists(String categoryName)
   at PerfCountersInstaller.CheckCounters()
   at NServiceBusPrerequisitesInstaller.PerfCounterSetupStep(Action`1 logOutput, Action`1 logError)

**Comment by SimonCropp** [comment]
it is possible your counters are corrupted. 

Can you try the workaround suggested here http://docs.particular.net/nservicebus/operations/performance-counters#corrupted-counters

**Comment by RonckVac** [comment]
You are right, it works!
thank you :)

**Comment by SimonCropp** [comment]
glad to help :)
